<?php

require_once dirname(__FILE__) . '/../../../controllers/ClienteController.php';

/**
 * Test class for ClienteController.
 * Generated by PHPUnit on 2012-07-10 at 20:14:47.
 */
class ClienteControllerTest extends CTestCase {

    /**
     * @var ClienteController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ClienteController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ClienteController::actionIndex
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClienteController::actionAdicionar
     * @todo Implement testActionAdicionar().
     */
    public function testActionAdicionar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClienteController::actionEditar
     * @todo Implement testActionEditar().
     */
    public function testActionEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClienteController::actionApagar
     * @todo Implement testActionApagar().
     */
    public function testActionApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClienteController::actionEmail
     * @todo Implement testActionEmail().
     */
    public function testActionEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClienteController::actionSms
     * @todo Implement testActionSms().
     */
    public function testActionSms() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClienteController::actionPassword
     * @todo Implement testActionPassword().
     */
    public function testActionPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClienteController::accessRules
     * @todo Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
