<?php

require_once dirname(__FILE__) . '/../../../controllers/FolhaObraController.php';

/**
 * Test class for FolhaObraController.
 * Generated by PHPUnit on 2012-07-10 at 20:14:47.
 */
class FolhaObraControllerTest extends CTestCase {

    /**
     * @var FolhaObraController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FolhaObraController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers FolhaObraController::actionIndex
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FolhaObraController::actionAdicionar
     * @todo Implement testActionAdicionar().
     */
    public function testActionAdicionar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FolhaObraController::actionEditar
     * @todo Implement testActionEditar().
     */
    public function testActionEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FolhaObraController::actionApagar
     * @todo Implement testActionApagar().
     */
    public function testActionApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FolhaObraController::actionFolhaDeMarcacao
     * @todo Implement testActionFolhaDeMarcacao().
     */
    public function testActionFolhaDeMarcacao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FolhaObraController::actionImprimir
     * @todo Implement testActionImprimir().
     */
    public function testActionImprimir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FolhaObraController::actionModelo
     * @todo Implement testActionModelo().
     */
    public function testActionModelo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FolhaObraController::accessRules
     * @todo Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
