<?php

require_once dirname(__FILE__) . '/../../../controllers/IvaController.php';

/**
 * Test class for IvaController.
 * Generated by PHPUnit on 2012-07-10 at 20:14:48.
 */
class IvaControllerTest extends CTestCase {

    /**
     * @var IvaController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IvaController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers IvaController::actionIndex
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IvaController::actionAdicionar
     * @todo Implement testActionAdicionar().
     */
    public function testActionAdicionar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IvaController::actionEditar
     * @todo Implement testActionEditar().
     */
    public function testActionEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IvaController::actionApagar
     * @todo Implement testActionApagar().
     */
    public function testActionApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IvaController::accessRules
     * @todo Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
