<?php

require_once dirname(__FILE__) . '/../../../controllers/MarcaController.php';

/**
 * Test class for MarcaController.
 * Generated by PHPUnit on 2012-07-10 at 20:14:48.
 */
class MarcaControllerTest extends CTestCase {

    /**
     * @var MarcaController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MarcaController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MarcaController::actionIndex
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarcaController::actionAdicionar
     * @todo Implement testActionAdicionar().
     */
    public function testActionAdicionar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarcaController::actionEditar
     * @todo Implement testActionEditar().
     */
    public function testActionEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarcaController::actionDelete
     * @todo Implement testActionDelete().
     */
    public function testActionDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarcaController::accessRules
     * @todo Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
