<?php

require_once dirname(__FILE__) . '/../../../controllers/MarcacaoController.php';

/**
 * Test class for MarcacaoController.
 * Generated by PHPUnit on 2012-07-10 at 20:14:49.
 */
class MarcacaoControllerTest extends CTestCase {

    /**
     * @var MarcacaoController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MarcacaoController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MarcacaoController::actionIndex
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarcacaoController::actionMarcar
     * @todo Implement testActionMarcar().
     */
    public function testActionMarcar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarcacaoController::actionApagar
     * @todo Implement testActionApagar().
     */
    public function testActionApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarcacaoController::actionEventos
     * @todo Implement testActionEventos().
     */
    public function testActionEventos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarcacaoController::actionActualizar
     * @todo Implement testActionActualizar().
     */
    public function testActionActualizar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarcacaoController::accessRules
     * @todo Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
