<?php

require_once dirname(__FILE__) . '/../../../controllers/PublicoController.php';

/**
 * Test class for PublicoController.
 * Generated by PHPUnit on 2012-07-10 at 20:14:49.
 */
class PublicoControllerTest extends CTestCase {

    /**
     * @var PublicoController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PublicoController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PublicoController::actionIndex
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PublicoController::actionSobre
     * @todo Implement testActionSobre().
     */
    public function testActionSobre() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PublicoController::actionContactos
     * @todo Implement testActionContactos().
     */
    public function testActionContactos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PublicoController::actionEntrar
     * @todo Implement testActionEntrar().
     */
    public function testActionEntrar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PublicoController::actionSair
     * @todo Implement testActionSair().
     */
    public function testActionSair() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PublicoController::actionErro
     * @todo Implement testActionErro().
     */
    public function testActionErro() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PublicoController::accessRules
     * @todo Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
