<?php

require_once dirname(__FILE__) . '/../../../controllers/RegistoController.php';

/**
 * Test class for RegistoController.
 * Generated by PHPUnit on 2012-07-10 at 20:14:50.
 */
class RegistoControllerTest extends CTestCase {

    /**
     * @var RegistoController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RegistoController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RegistoController::actionIndex
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistoController::actionSms
     * @todo Implement testActionSms().
     */
    public function testActionSms() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistoController::actionEmail
     * @todo Implement testActionEmail().
     */
    public function testActionEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistoController::actionDetalhesSms
     * @todo Implement testActionDetalhesSms().
     */
    public function testActionDetalhesSms() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistoController::actionDetalhes
     * @todo Implement testActionDetalhes().
     */
    public function testActionDetalhes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistoController::actionRemoverSms
     * @todo Implement testActionRemoverSms().
     */
    public function testActionRemoverSms() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistoController::actionRemoverEmail
     * @todo Implement testActionRemoverEmail().
     */
    public function testActionRemoverEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistoController::accessRules
     * @todo Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
