<?php

require_once dirname(__FILE__) . '/../../../controllers/VeiculoController.php';

/**
 * Test class for VeiculoController.
 * Generated by PHPUnit on 2012-07-10 at 20:14:50.
 */
class VeiculoControllerTest extends CTestCase {

    /**
     * @var VeiculoController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new VeiculoController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers VeiculoController::actionIndex
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VeiculoController::actionLista
     * @todo Implement testActionLista().
     */
    public function testActionLista() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VeiculoController::actionAdicionar
     * @todo Implement testActionAdicionar().
     */
    public function testActionAdicionar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VeiculoController::actionEditar
     * @todo Implement testActionEditar().
     */
    public function testActionEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VeiculoController::actionApagar
     * @todo Implement testActionApagar().
     */
    public function testActionApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VeiculoController::actionAcMatricula
     * @todo Implement testActionAcMatricula().
     */
    public function testActionAcMatricula() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VeiculoController::accessRules
     * @todo Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
