/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PainelClientes.java
 *
 * Created on Sep 3, 2010, 7:27:59 PM
 */

package net.sf.jautoinvoice.paineis;

/**
 *
 * @author knitter
 */
public class PainelClientes extends javax.swing.JPanel {

    /** Creates new form PainelClientes */
    public PainelClientes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspSplit = new javax.swing.JSplitPane();
        jpPainelLista = new javax.swing.JPanel();
        jtfPesquisa = new javax.swing.JTextField();
        jbtnRemoverCliente = new javax.swing.JButton();
        jbtnAdicionarCliente = new javax.swing.JButton();
        jscScroll = new javax.swing.JScrollPane();
        jtListaClientes = new javax.swing.JTree();
        jpPainelDados = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jspSplit.setDividerLocation(200);

        jtfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaActionPerformed(evt);
            }
        });

        jbtnRemoverCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/vcard_delete.png"))); // NOI18N
        jbtnRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverClienteActionPerformed(evt);
            }
        });

        jbtnAdicionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/vcard_add.png"))); // NOI18N
        jbtnAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarClienteActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jtListaClientes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jscScroll.setViewportView(jtListaClientes);

        javax.swing.GroupLayout jpPainelListaLayout = new javax.swing.GroupLayout(jpPainelLista);
        jpPainelLista.setLayout(jpPainelListaLayout);
        jpPainelListaLayout.setHorizontalGroup(
            jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPainelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPainelListaLayout.createSequentialGroup()
                        .addComponent(jbtnAdicionarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRemoverCliente))
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jscScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPainelListaLayout.setVerticalGroup(
            jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPainelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnRemoverCliente)
                    .addComponent(jbtnAdicionarCliente))
                .addContainerGap())
        );

        jspSplit.setLeftComponent(jpPainelLista);

        javax.swing.GroupLayout jpPainelDadosLayout = new javax.swing.GroupLayout(jpPainelDados);
        jpPainelDados.setLayout(jpPainelDadosLayout);
        jpPainelDadosLayout.setHorizontalGroup(
            jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        jpPainelDadosLayout.setVerticalGroup(
            jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jspSplit.setRightComponent(jpPainelDados);

        add(jspSplit, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisaActionPerformed

    private void jbtnRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRemoverClienteActionPerformed

    private void jbtnAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAdicionarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAdicionarCliente;
    private javax.swing.JButton jbtnRemoverCliente;
    private javax.swing.JPanel jpPainelDados;
    private javax.swing.JPanel jpPainelLista;
    private javax.swing.JScrollPane jscScroll;
    private javax.swing.JSplitPane jspSplit;
    private javax.swing.JTree jtListaClientes;
    private javax.swing.JTextField jtfPesquisa;
    // End of variables declaration//GEN-END:variables

}
