/*
 * PainelVeiculos.java
 *
 * This file is part of jAutoInvoice, http://sourceforge.net/p/jautoinvoice
 *
 * Copyright (C) 2010  Sérgio Lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.sf.jautoinvoice.paineis;

import javax.swing.ImageIcon;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import net.sf.jautoinvoice.JAutoInvoiceApp;
import net.sf.jautoinvoice.engine.Veiculo;

public class PainelVeiculos extends javax.swing.JPanel {

    private JAutoInvoiceApp app;
    private Veiculo actual;
    //
    private DefaultTreeCellRenderer renderer;
    private DefaultMutableTreeNode root;
    private boolean pesquisa;

    public PainelVeiculos(JAutoInvoiceApp app) {
        this.app = app;

        actual = null;
        pesquisa = false;

        root = new DefaultMutableTreeNode("Veículos");

        processarListaVeiculos();

        ImageIcon rootIcon = new ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/car.png"));
        renderer = new DefaultTreeCellRenderer();
        renderer.setClosedIcon(rootIcon);
        renderer.setOpenIcon(rootIcon);
        renderer.setLeafIcon(rootIcon);

        initComponents();
    }

    private void processarListaVeiculos() {
        DefaultMutableTreeNode elem;
        //for (Veiculo v : app.getGestor().listarTodosVeiculos()) {
        //    elem = new DefaultMutableTreeNode(v);
        //    root.add(elem);
        //}
    }

    private void mostrarDadosVeiculo() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspSplit = new javax.swing.JSplitPane();
        jpPainelLista = new javax.swing.JPanel();
        jtfPesquisa = new javax.swing.JTextField();
        jbtnRemoverVeiculo = new javax.swing.JButton();
        jbtnAdicionarVeiculo = new javax.swing.JButton();
        jscpScrollVeiculos = new javax.swing.JScrollPane();
        jtVeiculos = new javax.swing.JTree();
        jpPainelDireita = new javax.swing.JPanel();
        jpPainelDados = new javax.swing.JPanel();
        jlblMarca = new javax.swing.JLabel();
        jcbxMarca = new javax.swing.JComboBox();
        jcbxModelo = new javax.swing.JComboBox();
        jlblModelo = new javax.swing.JLabel();
        jlblNrChassis = new javax.swing.JLabel();
        jlblCilindrada = new javax.swing.JLabel();
        jtfNrChassis = new javax.swing.JTextField();
        jtfCilindrada = new javax.swing.JTextField();
        jtfNrMotor = new javax.swing.JTextField();
        jlblNrMotor = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Registo = new javax.swing.JLabel();
        jtfMatricula = new javax.swing.JTextField();
        jlblMatricula = new javax.swing.JLabel();
        jcbxDono = new javax.swing.JComboBox();
        jlblDono = new javax.swing.JLabel();
        jbtnAdicionarCliente = new javax.swing.JButton();
        jpPainelObservacoes = new javax.swing.JPanel();
        jscpObservacoes = new javax.swing.JScrollPane();
        jtaObservacoes = new javax.swing.JTextArea();
        jpDonosAntigos = new javax.swing.JPanel();
        jcbxDonosAntigos = new javax.swing.JComboBox();
        jbtnRemoverDonoAntigo = new javax.swing.JButton();
        jbtnAdicionarDonoAntigo = new javax.swing.JButton();
        jscpDonosAntigos = new javax.swing.JScrollPane();
        jlstDonosAntigos = new javax.swing.JList();
        jbtnGravar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jspSplit.setDividerLocation(200);

        jbtnRemoverVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/car_delete.png"))); // NOI18N

        jbtnAdicionarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/car_add.png"))); // NOI18N

        jtVeiculos.setModel(new DefaultTreeModel(root));
        jtVeiculos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jtVeiculosValueChanged(evt);
            }
        });
        jscpScrollVeiculos.setViewportView(jtVeiculos);

        javax.swing.GroupLayout jpPainelListaLayout = new javax.swing.GroupLayout(jpPainelLista);
        jpPainelLista.setLayout(jpPainelListaLayout);
        jpPainelListaLayout.setHorizontalGroup(
            jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPainelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPainelListaLayout.createSequentialGroup()
                        .addComponent(jbtnAdicionarVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRemoverVeiculo))
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jscpScrollVeiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPainelListaLayout.setVerticalGroup(
            jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPainelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpScrollVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnRemoverVeiculo)
                    .addComponent(jbtnAdicionarVeiculo))
                .addContainerGap())
        );

        jspSplit.setLeftComponent(jpPainelLista);

        jpPainelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Veículo"));

        jlblMarca.setText("Marca");

        jlblModelo.setText("Modelo");

        jlblNrChassis.setText("Nr. Chassis");

        jlblCilindrada.setText("Cilidranda");

        jlblNrMotor.setText("Nr. Motor");

        jTextField5.setText("<Substituir por DatePicker>");

        Registo.setText("Registo");

        jlblMatricula.setText("Matrícula");

        jlblDono.setText("Dono");

        jbtnAdicionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/add.png"))); // NOI18N

        jpPainelObservacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações"));

        jtaObservacoes.setColumns(20);
        jtaObservacoes.setRows(5);
        jscpObservacoes.setViewportView(jtaObservacoes);

        javax.swing.GroupLayout jpPainelObservacoesLayout = new javax.swing.GroupLayout(jpPainelObservacoes);
        jpPainelObservacoes.setLayout(jpPainelObservacoesLayout);
        jpPainelObservacoesLayout.setHorizontalGroup(
            jpPainelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelObservacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpPainelObservacoesLayout.setVerticalGroup(
            jpPainelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelObservacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpDonosAntigos.setBorder(javax.swing.BorderFactory.createTitledBorder("Donos Antigos"));

        jbtnRemoverDonoAntigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/delete.png"))); // NOI18N

        jbtnAdicionarDonoAntigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/add.png"))); // NOI18N

        jscpDonosAntigos.setViewportView(jlstDonosAntigos);

        javax.swing.GroupLayout jpDonosAntigosLayout = new javax.swing.GroupLayout(jpDonosAntigos);
        jpDonosAntigos.setLayout(jpDonosAntigosLayout);
        jpDonosAntigosLayout.setHorizontalGroup(
            jpDonosAntigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDonosAntigosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDonosAntigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscpDonosAntigos, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addGroup(jpDonosAntigosLayout.createSequentialGroup()
                        .addComponent(jcbxDonosAntigos, 0, 325, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAdicionarDonoAntigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRemoverDonoAntigo)))
                .addContainerGap())
        );
        jpDonosAntigosLayout.setVerticalGroup(
            jpDonosAntigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDonosAntigosLayout.createSequentialGroup()
                .addGroup(jpDonosAntigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxDonosAntigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRemoverDonoAntigo)
                    .addComponent(jbtnAdicionarDonoAntigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpDonosAntigos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPainelDadosLayout = new javax.swing.GroupLayout(jpPainelDados);
        jpPainelDados.setLayout(jpPainelDadosLayout);
        jpPainelDadosLayout.setHorizontalGroup(
            jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPainelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpDonosAntigos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPainelObservacoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPainelDadosLayout.createSequentialGroup()
                        .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPainelDadosLayout.createSequentialGroup()
                                    .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlblModelo)
                                        .addComponent(jlblMarca))
                                    .addGap(38, 38, 38)
                                    .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jcbxMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcbxModelo, 0, 255, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPainelDadosLayout.createSequentialGroup()
                                    .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlblCilindrada)
                                        .addComponent(jlblNrChassis)
                                        .addComponent(jlblNrMotor)
                                        .addComponent(Registo)
                                        .addComponent(jlblMatricula))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfNrChassis, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                        .addComponent(jcbxDono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfMatricula)
                                        .addComponent(jtfNrMotor, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jlblDono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpPainelDadosLayout.setVerticalGroup(
            jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNrChassis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblNrChassis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCilindrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNrMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblNrMotor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDono)
                    .addComponent(jbtnAdicionarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPainelObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDonosAntigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnGravar.setText("Gravar");

        javax.swing.GroupLayout jpPainelDireitaLayout = new javax.swing.GroupLayout(jpPainelDireita);
        jpPainelDireita.setLayout(jpPainelDireitaLayout);
        jpPainelDireitaLayout.setHorizontalGroup(
            jpPainelDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelDireitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPainelDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPainelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnGravar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jpPainelDireitaLayout.setVerticalGroup(
            jpPainelDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelDireitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPainelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnGravar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jspSplit.setRightComponent(jpPainelDireita);

        add(jspSplit, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtVeiculosValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jtVeiculosValueChanged
        if (jtVeiculos.getLastSelectedPathComponent().toString().equalsIgnoreCase("Veículos")) {
            actual = null;
            //semVeiculoSeleccionado();
            //jbtnRemoverVeiculo.setEnabled(false);
        } else {
            actual = (Veiculo) ((DefaultMutableTreeNode) jtVeiculos.getLastSelectedPathComponent()).getUserObject();
            //jbtnRemoverVeiculo.setEnabled(false);
            mostrarDadosVeiculo();
        }
    }//GEN-LAST:event_jtVeiculosValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Registo;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton jbtnAdicionarCliente;
    private javax.swing.JButton jbtnAdicionarDonoAntigo;
    private javax.swing.JButton jbtnAdicionarVeiculo;
    private javax.swing.JButton jbtnGravar;
    private javax.swing.JButton jbtnRemoverDonoAntigo;
    private javax.swing.JButton jbtnRemoverVeiculo;
    private javax.swing.JComboBox jcbxDono;
    private javax.swing.JComboBox jcbxDonosAntigos;
    private javax.swing.JComboBox jcbxMarca;
    private javax.swing.JComboBox jcbxModelo;
    private javax.swing.JLabel jlblCilindrada;
    private javax.swing.JLabel jlblDono;
    private javax.swing.JLabel jlblMarca;
    private javax.swing.JLabel jlblMatricula;
    private javax.swing.JLabel jlblModelo;
    private javax.swing.JLabel jlblNrChassis;
    private javax.swing.JLabel jlblNrMotor;
    private javax.swing.JList jlstDonosAntigos;
    private javax.swing.JPanel jpDonosAntigos;
    private javax.swing.JPanel jpPainelDados;
    private javax.swing.JPanel jpPainelDireita;
    private javax.swing.JPanel jpPainelLista;
    private javax.swing.JPanel jpPainelObservacoes;
    private javax.swing.JScrollPane jscpDonosAntigos;
    private javax.swing.JScrollPane jscpObservacoes;
    private javax.swing.JScrollPane jscpScrollVeiculos;
    private javax.swing.JSplitPane jspSplit;
    private javax.swing.JTree jtVeiculos;
    private javax.swing.JTextArea jtaObservacoes;
    private javax.swing.JTextField jtfCilindrada;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfNrChassis;
    private javax.swing.JTextField jtfNrMotor;
    private javax.swing.JTextField jtfPesquisa;
    // End of variables declaration//GEN-END:variables
}
