/*
 * PainelPecas.java
 *
 * This file is part of jAutoInvoice, http://sourceforge.net/p/jautoinvoice
 *
 * Copyright (C) 2010  Sérgio Lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.sf.jautoinvoice.paineis;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import net.sf.jautoinvoice.JAutoInvoiceApp;
import net.sf.jautoinvoice.engine.Peca;

public class PainelPecas extends javax.swing.JPanel {

    private JAutoInvoiceApp app;
    private Peca actual;
    //
    private DefaultTreeCellRenderer renderer;
    private DefaultMutableTreeNode root;
    private boolean pesquisa;
    public PainelPecas(JAutoInvoiceApp app) {
        this.app = app;

        actual = null;
        pesquisa = false;
        root = new DefaultMutableTreeNode("Peças");

        processarListaPecas();

        ImageIcon rootIcon = new ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/wrench_orange.png"));
        renderer = new DefaultTreeCellRenderer();
        renderer.setClosedIcon(rootIcon);
        renderer.setOpenIcon(rootIcon);
        renderer.setLeafIcon(rootIcon);

        initComponents();
    }

    private void processarListaPecas() {
        DefaultMutableTreeNode elem;
        for (Peca p : app.getGestor().listarTodasPecas()) {
            elem = new DefaultMutableTreeNode(p);
            root.add(elem);
        }
    }

    private void mostrarDadosPeca() {

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspSplit = new javax.swing.JSplitPane();
        jpPainelLista = new javax.swing.JPanel();
        jtfPesquisa = new javax.swing.JTextField();
        jbtnRemoverPeca = new javax.swing.JButton();
        jbtnAdicionarPeca = new javax.swing.JButton();
        jscpScroll = new javax.swing.JScrollPane();
        jtListaPecas = new javax.swing.JTree();
        jpPainelDireito = new javax.swing.JPanel();
        jpDados = new javax.swing.JPanel();
        jblNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlblReferencia = new javax.swing.JLabel();
        jlblPreco = new javax.swing.JLabel();
        jtfReferencia = new javax.swing.JTextField();
        jffPreco = new javax.swing.JFormattedTextField();
        jpPainelDescricao = new javax.swing.JPanel();
        jspScrollDescricao = new javax.swing.JScrollPane();
        jtaDescricao = new javax.swing.JTextArea();
        jlblMoeda = new javax.swing.JLabel();
        jpPainelModelos = new javax.swing.JPanel();
        jscpScrollTreeModelos = new javax.swing.JScrollPane();
        jtModelos = new javax.swing.JTree();
        jpBotoes = new javax.swing.JPanel();
        jbtnAdicionarModelo = new javax.swing.JButton();
        jbtnRemoverModelo = new javax.swing.JButton();
        jscpScrollModelos = new javax.swing.JScrollPane();
        jlstListaModelos = new javax.swing.JList();
        jlblIva = new javax.swing.JLabel();
        jcbxIva = new javax.swing.JComboBox();
        jbtnGravar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jspSplit.setDividerLocation(200);

        jtfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaActionPerformed(evt);
            }
        });

        jbtnRemoverPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/brick_delete.png"))); // NOI18N
        jbtnRemoverPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverPecaActionPerformed(evt);
            }
        });

        jbtnAdicionarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/brick_add.png"))); // NOI18N
        jbtnAdicionarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarPecaActionPerformed(evt);
            }
        });

        jtListaPecas.setModel(new DefaultTreeModel(root));
        jtListaPecas.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jtListaPecasValueChanged(evt);
            }
        });
        jscpScroll.setViewportView(jtListaPecas);

        javax.swing.GroupLayout jpPainelListaLayout = new javax.swing.GroupLayout(jpPainelLista);
        jpPainelLista.setLayout(jpPainelListaLayout);
        jpPainelListaLayout.setHorizontalGroup(
            jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPainelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPainelListaLayout.createSequentialGroup()
                        .addComponent(jbtnAdicionarPeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRemoverPeca))
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jscpScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPainelListaLayout.setVerticalGroup(
            jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPainelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnRemoverPeca)
                    .addComponent(jbtnAdicionarPeca))
                .addContainerGap())
        );

        jspSplit.setLeftComponent(jpPainelLista);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/jautoinvoice/i18n/principal"); // NOI18N
        jpDados.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("PainelPecas.jpDados.border.title"))); // NOI18N

        jblNome.setText(bundle.getString("PainelPecas.jblNome.text")); // NOI18N

        jlblReferencia.setText(bundle.getString("PainelPecas.jlblReferencia.text")); // NOI18N

        jlblPreco.setText(bundle.getString("PainelPecas.jlblPreco.text")); // NOI18N

        jtfReferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfReferenciaFocusLost(evt);
            }
        });

        jpPainelDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("PainelPecas.jpPainelDescricao.border.title"))); // NOI18N

        jtaDescricao.setColumns(20);
        jtaDescricao.setRows(5);
        jspScrollDescricao.setViewportView(jtaDescricao);

        javax.swing.GroupLayout jpPainelDescricaoLayout = new javax.swing.GroupLayout(jpPainelDescricao);
        jpPainelDescricao.setLayout(jpPainelDescricaoLayout);
        jpPainelDescricaoLayout.setHorizontalGroup(
            jpPainelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPainelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspScrollDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpPainelDescricaoLayout.setVerticalGroup(
            jpPainelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelDescricaoLayout.createSequentialGroup()
                .addComponent(jspScrollDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlblMoeda.setText(bundle.getString("PainelPecas.jlblMoeda.text")); // NOI18N

        jpPainelModelos.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("PainelPecas.jpPainelModelos.border.title"))); // NOI18N
        jpPainelModelos.setLayout(new javax.swing.BoxLayout(jpPainelModelos, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jtModelos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jscpScrollTreeModelos.setViewportView(jtModelos);

        jpPainelModelos.add(jscpScrollTreeModelos);

        jpBotoes.setLayout(new javax.swing.BoxLayout(jpBotoes, javax.swing.BoxLayout.Y_AXIS));

        jbtnAdicionarModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/arrow_right.png"))); // NOI18N
        jbtnAdicionarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarModeloActionPerformed(evt);
            }
        });
        jpBotoes.add(jbtnAdicionarModelo);

        jbtnRemoverModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/arrow_left.png"))); // NOI18N
        jbtnRemoverModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverModeloActionPerformed(evt);
            }
        });
        jpBotoes.add(jbtnRemoverModelo);

        jpPainelModelos.add(jpBotoes);

        jscpScrollModelos.setViewportView(jlstListaModelos);

        jpPainelModelos.add(jscpScrollModelos);

        jlblIva.setText(bundle.getString("PainelPecas.jlblIva.text")); // NOI18N

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPainelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPainelModelos, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblNome)
                            .addComponent(jlblReferencia)
                            .addComponent(jlblPreco)
                            .addComponent(jlblIva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDadosLayout.createSequentialGroup()
                                .addComponent(jffPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlblMoeda))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfReferencia, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbxIva, javax.swing.GroupLayout.Alignment.LEADING, 0, 226, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblReferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jffPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPreco)
                    .addComponent(jlblMoeda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPainelModelos, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPainelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jbtnGravar.setText(bundle.getString("PainelPecas.jbtnGravar.text")); // NOI18N

        javax.swing.GroupLayout jpPainelDireitoLayout = new javax.swing.GroupLayout(jpPainelDireito);
        jpPainelDireito.setLayout(jpPainelDireitoLayout);
        jpPainelDireitoLayout.setHorizontalGroup(
            jpPainelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelDireitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPainelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnGravar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jpPainelDireitoLayout.setVerticalGroup(
            jpPainelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelDireitoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspSplit.setRightComponent(jpPainelDireito);

        add(jspSplit, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaActionPerformed
        JOptionPane.showMessageDialog(this, "Por implementar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jtfPesquisaActionPerformed

    private void jbtnRemoverPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverPecaActionPerformed
        JOptionPane.showMessageDialog(this, "Por implementar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnRemoverPecaActionPerformed

    private void jbtnAdicionarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarPecaActionPerformed
        JOptionPane.showMessageDialog(this, "Por implementar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnAdicionarPecaActionPerformed

    private void jbtnAdicionarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarModeloActionPerformed
        JOptionPane.showMessageDialog(this, "Por implementar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnAdicionarModeloActionPerformed

    private void jbtnRemoverModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverModeloActionPerformed
        JOptionPane.showMessageDialog(this, "Por implementar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnRemoverModeloActionPerformed

    private void jtfReferenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfReferenciaFocusLost
       //TODO:
    }//GEN-LAST:event_jtfReferenciaFocusLost

    private void jtListaPecasValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jtListaPecasValueChanged
         if (jtListaPecas.getLastSelectedPathComponent().toString().equalsIgnoreCase("Peças")) {
            actual = null;
            //semPecaSeleccionado();
            //jbtnRemoverPeca.setEnabled(false);
        } else {
            actual = (Peca) ((DefaultMutableTreeNode) jtListaPecas.getLastSelectedPathComponent()).getUserObject();
            //jbtnRemoverPeca.setEnabled(false);
            mostrarDadosPeca();
        }
    }//GEN-LAST:event_jtListaPecasValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblNome;
    private javax.swing.JButton jbtnAdicionarModelo;
    private javax.swing.JButton jbtnAdicionarPeca;
    private javax.swing.JButton jbtnGravar;
    private javax.swing.JButton jbtnRemoverModelo;
    private javax.swing.JButton jbtnRemoverPeca;
    private javax.swing.JComboBox jcbxIva;
    private javax.swing.JFormattedTextField jffPreco;
    private javax.swing.JLabel jlblIva;
    private javax.swing.JLabel jlblMoeda;
    private javax.swing.JLabel jlblPreco;
    private javax.swing.JLabel jlblReferencia;
    private javax.swing.JList jlstListaModelos;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpPainelDescricao;
    private javax.swing.JPanel jpPainelDireito;
    private javax.swing.JPanel jpPainelLista;
    private javax.swing.JPanel jpPainelModelos;
    private javax.swing.JScrollPane jscpScroll;
    private javax.swing.JScrollPane jscpScrollModelos;
    private javax.swing.JScrollPane jscpScrollTreeModelos;
    private javax.swing.JScrollPane jspScrollDescricao;
    private javax.swing.JSplitPane jspSplit;
    private javax.swing.JTree jtListaPecas;
    private javax.swing.JTree jtModelos;
    private javax.swing.JTextArea jtaDescricao;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfReferencia;
    // End of variables declaration//GEN-END:variables

}
