CREATE TABLE `Cliente` (
`idCliente` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`email` VARCHAR( 255 ) NULL ,
`password` VARCHAR( 40 ) NULL ,
`nome` VARCHAR( 255 ) NOT NULL ,
`contribuinte` VARCHAR( 9 ) NOT NULL ,
`telefone` VARCHAR ( 9 ) NULL ,
`telemovel` VARCHAR ( 9 ) NULL ,
`morada` VARCHAR( 255 ) NULL ,
`activo` TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Funcionario` (
`idFuncionario` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`username` VARCHAR( 100 ) NOT NULL UNIQUE ,
`password` VARCHAR( 40 ) NOT NULL ,
`valorHora` DECIMAL (10,4) NULL ,
`nome` VARCHAR( 255 ) NOT NULL ,
`contribuinte` VARCHAR( 9 ) NOT NULL ,
`activo` TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Fornecedor` (
`idFornecedor` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`nome` VARCHAR( 255 ) NOT NULL ,
`email` VARCHAR( 255 ) NULL ,
`notas` TEXT NULL ,
`telefone` VARCHAR ( 9 ) NULL ,
`telemovel` VARCHAR ( 9 ) NULL ,
`website` VARCHAR ( 255 ) NULL ,
`morada` VARCHAR( 255 ) NULL ,
`activo` TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Marca` (
`idMarca` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`nome` VARCHAR ( 100 ) NOT NULL UNIQUE ,
`activo` TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Modelo` (
`idModelo` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`nome` VARCHAR( 100 ) NOT NULL UNIQUE ,
`activo` TINYINT NOT NULL DEFAULT 1,
`idMarca` INT UNSIGNED NOT NULL ,
CONSTRAINT `fkModeloMarca` FOREIGN KEY (`idMarca`) REFERENCES `Marca`(`idMarca`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Categoria` (
`idCategoria` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`nome` VARCHAR( 100 ) NOT NULL UNIQUE ,
`activo` TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Combustivel` (
`idCombustivel` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`nome` VARCHAR( 100 ) NOT NULL UNIQUE ,
`activo` TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Veiculo` (
`idVeiculo` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`dataRegisto` DATE NULL ,
`matricula` VARCHAR( 12 ) NOT NULL ,
`nrChassis` VARCHAR( 25 ) NULL ,
`cilindrada` VARCHAR( 25 ) NULL ,
`nrMotor` VARCHAR( 25 ) NULL ,   
`notas` TEXT NULL ,
`activo` TINYINT NOT NULL DEFAULT 1 ,
`idCliente` INT UNSIGNED NOT NULL ,
`idCategoria` INT UNSIGNED NOT NULL ,
`idCombustivel` INT UNSIGNED NOT NULL ,
`idModelo` INT UNSIGNED NOT NULL ,
CONSTRAINT `fkVeiculoCliente` FOREIGN KEY (`idCliente`) REFERENCES `Cliente`(`idCliente`) ,
CONSTRAINT `fkVeiculoCategoria` FOREIGN KEY (`idCategoria`) REFERENCES `Categoria`(`idCategoria`) ,
CONSTRAINT `fkVeiculoCombustivel` FOREIGN KEY (`idCombustivel`) REFERENCES `Combustivel`(`idCombustivel`) ,
CONSTRAINT `fkVeiculoModelo` FOREIGN KEY (`idModelo`) REFERENCES `Modelo`(`idModelo`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `ClienteVeiculo` (
`idVeiculo` INT UNSIGNED NOT NULL ,
`idCliente` INT UNSIGNED NOT NULL ,
PRIMARY KEY (`idVeiculo`, `idCliente`),
CONSTRAINT `fkClienteVeiculoCliente` FOREIGN KEY (`idCliente`) REFERENCES `Cliente`(`idCliente`) ,
CONSTRAINT `fkClienteVeiculoVeiculo` FOREIGN KEY (`idVeiculo`) REFERENCES `Veiculo`(`idVeiculo`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE `FolhaObra` (
`idFolhaObra` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`data` DATETIME NOT NULL ,
`descricaoAvaria` TEXT NOT NULL ,
`kms` INT NOT NULL ,
`activo` TINYINT NOT NULL DEFAULT 1,
`idVeiculo` INT UNSIGNED NOT NULL ,
`idFuncionario` INT UNSIGNED NOT NULL ,
CONSTRAINT `FolhaObraVeiculo` FOREIGN KEY (`idVeiculo`) REFERENCES `Veiculo`(`idVeiculo`) ,
CONSTRAINT `FolhaObraFuncionario` FOREIGN KEY (`idFuncionario`) REFERENCES `Funcionario`(`idFuncionario`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `IVA` (
`idIVA` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`descricao` VARCHAR( 255 ) NOT NULL ,
`percentagem` DOUBLE NOT NULL ,
`activo` TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Material` (
`idMaterial` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`precoUnitario` DECIMAL( 10,4 ) NOT NULL ,
`referencia` VARCHAR ( 25 ) NOT NULL ,
`descricao` TEXT NULL ,
`activo` TINYINT NOT NULL DEFAULT 1,
`idFornecedor` INT UNSIGNED NOT NULL ,
`idIVA` INT UNSIGNED NOT NULL ,
CONSTRAINT `fkMaterialFornecedor` FOREIGN KEY (`idFornecedor`) REFERENCES `Fornecedor`(`idFornecedor`) ,
CONSTRAINT `fkMaterialIVA` FOREIGN KEY (`idIVA`) REFERENCES `IVA`(`idIVA`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Marcacao` (
`idMarcacao` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`dataMarcacao` DATETIME NOT NULL ,
`idFolhaObra` INT UNSIGNED NULL ,
`idVeiculo` INT UNSIGNED NULL ,
`criado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`activo` TINYINT NOT NULL DEFAULT 1 ,
CONSTRAINT `fkMFolhaObra` FOREIGN KEY (`idFolhaObra`) REFERENCES `FolhaObra`(`idFolhaObra`) ,
CONSTRAINT `fkMVeiculo` FOREIGN KEY (`idVeiculo`) REFERENCES `Veiculo`(`idVeiculo`) 
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `Servico` (
`idServico` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`nome` VARCHAR( 255 ) NOT NULL UNIQUE ,
`descricao` TEXT NULL ,
`activo` TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

CREATE TABLE `LinhaServico` (
`idLinhaServico` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`duracao` DOUBLE NOT NULL ,
`valorHora` DECIMAL( 10,4 ) NOT NULL ,
`notas` TEXT NULL ,
`activo` TINYINT NOT NULL DEFAULT 1 ,
`idFuncionario` INT UNSIGNED NOT NULL ,
`idServico`  INT UNSIGNED NOT NULL ,
`idFolhaObra` INT UNSIGNED NOT NULL ,
CONSTRAINT `fkLinhaServicoFuncionario` FOREIGN KEY (`idFuncionario`) REFERENCES `Funcionario`(`idFuncionario`) ,
CONSTRAINT `fkLinhaServicoFolhaObra` FOREIGN KEY (`idFolhaObra`) REFERENCES `FolhaObra`(`idFolhaObra`) ,
CONSTRAINT `fkLinhaServicoServico` FOREIGN KEY (`idServico`) REFERENCES `Servico`(`idServico`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ;

/*
CREATE TABLE `LinhaGasto` (
`idLinhaGasto` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`quantidade` TINYINT NOT NULL ,
`precoUnitario` DECIMAL( 10,4 ) NOT NULL , 
`activo` TINYINT NOT NULL DEFAULT 1 ,
`idMaterial` INT UNSIGNED NOT NULL ,
`idLInhaServico` INT UNSIGNED NOT NULL ,
CONSTRAINT `fkLinhaGastoMaterial` FOREIGN KEY (`idMaterial`) REFERENCES `Material`(`idMaterial`) ,
CONSTRAINT `fkLinhaGastoLinhaServico` FOREIGN KEY (`idLinhaServico`) REFERENCES `LinhaServico`(`idLinhaServico`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ; */