<?php

require_once dirname(__FILE__) . '/../../../models/MaterialFornecedor.php';

/**
 * Test class for MaterialFornecedor.
 * Generated by PHPUnit on 2012-07-10 at 20:18:18.
 */
class MaterialFornecedorTest extends CDbTestCase {

    /**
     * @var MaterialFornecedor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MaterialFornecedor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MaterialFornecedor::model
     * @todo Implement testModel().
     */
    public function testModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MaterialFornecedor::tableName
     * @todo Implement testTableName().
     */
    public function testTableName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MaterialFornecedor::relations
     * @todo Implement testRelations().
     */
    public function testRelations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
