/*
 * Reparacao.java
 *
 * This file is part of jAutoInvoice, http://sourceforge.net/p/jautoinvoice
 *
 * Copyright (C) 2010  Sérgio Lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.sf.jautoinvoice.janelas;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import net.sf.jautoinvoice.JAutoInvoiceApp;
import net.sf.jautoinvoice.engine.Categoria;
import net.sf.jautoinvoice.engine.Gestor;
import net.sf.jautoinvoice.engine.Iva;
import net.sf.jautoinvoice.engine.Log;
import net.sf.jautoinvoice.engine.Retencao;

public class Configuracoes extends javax.swing.JDialog {

    private Properties configuracoes;
    private DefaultListModel modeloIvas;
    private DefaultListModel modeloRetencoes;
    private DefaultListModel modeloCategorias;
    private DefaultListModel modeloLogs;
    private Gestor gestor;
    //
    private JFileChooser jfc;
    private boolean modificado;

    public Configuracoes(java.awt.Frame parent, boolean modal, Properties configuracoes) {
        super(parent, modal);
        gestor = ((JAutoInvoiceApp) parent).getGestor();

        this.configuracoes = configuracoes;

        String base = System.getProperty("user.home") + File.separator + ".jautoinvoice"
                + File.separator + "dados.db4o.inv";

        configuracoes.getProperty("caminho", base);
        int tipoAnimacao = Integer.parseInt(configuracoes.getProperty("tipo-animacao", "0"));
        boolean animacao = Boolean.parseBoolean(configuracoes.getProperty("animacao", "false"));
        int look = Integer.parseInt(configuracoes.getProperty("look", "0"));

        modeloIvas = new DefaultListModel();
        for (Iva i : gestor.listarTodosIvas()) {
            modeloIvas.addElement(i);
        }

        modeloRetencoes = new DefaultListModel();
        for (Retencao r : gestor.listarTodasRetencoes()) {
            modeloRetencoes.addElement(r);
        }

        modeloCategorias = new DefaultListModel();
        for (Categoria c : gestor.listarTodasCategorias()) {
            modeloCategorias.addElement(c);
        }

        modeloLogs = new DefaultListModel();
        for (Log l : gestor.listarTodosLogs()) {
            modeloLogs.addElement(l);
        }

        initComponents();

        jckbUsarAnimacao.setSelected(animacao);
        jcbxLookAndFeel.setSelectedIndex(look);
        jcbxTipoAnimacao.setSelectedIndex(tipoAnimacao);
    }

    @Override
    public void setVisible(boolean visible) {
        setLocation(getParent().getX() + (getParent().getWidth() / 2) - (getWidth() / 2),
                getParent().getY() + (getParent().getHeight() / 2) - (getHeight() / 2));

        super.setVisible(visible);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnCancelar = new javax.swing.JButton();
        jbtnGravar = new javax.swing.JButton();
        jtpTabs = new javax.swing.JTabbedPane();
        jpTabGeral = new javax.swing.JPanel();
        jpPainelGeral = new javax.swing.JPanel();
        jlblFicheiroDados = new javax.swing.JLabel();
        jtfFicheiroDados = new javax.swing.JTextField();
        jlblPassword = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        jpfPassword2 = new javax.swing.JPasswordField();
        jlblPassword2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnExplorar = new javax.swing.JButton();
        jpPainelAspecto = new javax.swing.JPanel();
        jlblLookAndFeel = new javax.swing.JLabel();
        jcbxLookAndFeel = new javax.swing.JComboBox();
        jckbUsarAnimacao = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jlblTipoAnimacao = new javax.swing.JLabel();
        jcbxTipoAnimacao = new javax.swing.JComboBox();
        jpTabIvas = new javax.swing.JPanel();
        jpPainelIvas = new javax.swing.JPanel();
        jlblDescricaoIva = new javax.swing.JLabel();
        jtfNomeIva = new javax.swing.JTextField();
        jlblValorIva = new javax.swing.JLabel();
        jffValorIva = new javax.swing.JFormattedTextField();
        jscpIvas = new javax.swing.JScrollPane();
        jlstIvas = new javax.swing.JList();
        jbtnAdicionarIva = new javax.swing.JButton();
        jbtnRemoverIva = new javax.swing.JButton();
        jpPainelRetencoes = new javax.swing.JPanel();
        jtfNomeRetencao = new javax.swing.JTextField();
        jffValorRetencao = new javax.swing.JFormattedTextField();
        jlblDescricaoRetencao = new javax.swing.JLabel();
        jlblValorRetencao = new javax.swing.JLabel();
        jscpRetencoes = new javax.swing.JScrollPane();
        jlstRetencoes = new javax.swing.JList();
        jbtnAdicionarRetencao = new javax.swing.JButton();
        jbtnRemoverRetencao = new javax.swing.JButton();
        jpTabCategorias = new javax.swing.JPanel();
        jpPainelCategorias = new javax.swing.JPanel();
        jlblNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jbtnAdicionarCategoria = new javax.swing.JButton();
        jbtnRemoverCategoria = new javax.swing.JButton();
        jscpCategorias = new javax.swing.JScrollPane();
        jlstCategorias = new javax.swing.JList();
        jpTabLogs = new javax.swing.JPanel();
        jpPainelLogs = new javax.swing.JPanel();
        jscpListaLogs = new javax.swing.JScrollPane();
        jlstListaLogs = new javax.swing.JList();
        jscpDadosLog = new javax.swing.JScrollPane();
        jtaDadosLog = new javax.swing.JTextArea();
        jbtnLimparLogs = new javax.swing.JButton();
        jbtExportarLogs = new javax.swing.JButton();
        jdcFiltroDatas = new com.toedter.calendar.JDateChooser();
        jbtnAplicarFiltroDatas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/jautoinvoice/i18n/dialogos"); // NOI18N
        setTitle(bundle.getString("Configuracoes.title")); // NOI18N

        jbtnCancelar.setText(bundle.getString("Configuracoes.jbtnCancelar.text")); // NOI18N
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnGravar.setText(bundle.getString("Configuracoes.jbtnGravar.text")); // NOI18N
        jbtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGravarActionPerformed(evt);
            }
        });

        jpPainelGeral.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Configuracoes.jpPainelGeral.border.title"))); // NOI18N

        jlblFicheiroDados.setText(bundle.getString("Configuracoes.jlblFicheiroDados.text")); // NOI18N

        jlblPassword.setText(bundle.getString("Configuracoes.jlblPassword.text")); // NOI18N

        jpfPassword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpfPassword2FocusLost(evt);
            }
        });

        jlblPassword2.setText(bundle.getString("Configuracoes.jlblPassword2.text")); // NOI18N

        jbtnExplorar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/folders_explorer.png"))); // NOI18N
        jbtnExplorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExplorarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpPainelGeralLayout = new org.jdesktop.layout.GroupLayout(jpPainelGeral);
        jpPainelGeral.setLayout(jpPainelGeralLayout);
        jpPainelGeralLayout.setHorizontalGroup(
            jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpPainelGeralLayout.createSequentialGroup()
                        .add(jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                            .add(jpPainelGeralLayout.createSequentialGroup()
                                .add(jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jlblPassword)
                                    .add(jlblPassword2))
                                .add(18, 18, 18)
                                .add(jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jpfPassword2)
                                    .add(jpfPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 212, Short.MAX_VALUE)))
                        .addContainerGap())
                    .add(jpPainelGeralLayout.createSequentialGroup()
                        .add(jlblFicheiroDados)
                        .add(18, 18, 18)
                        .add(jtfFicheiroDados, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnExplorar)
                        .add(40, 40, 40))))
        );
        jpPainelGeralLayout.setVerticalGroup(
            jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jlblFicheiroDados)
                        .add(jtfFicheiroDados, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jbtnExplorar))
                .add(18, 18, 18)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblPassword)
                    .add(jpfPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpPainelGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jpfPassword2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblPassword2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPainelAspecto.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Configuracoes.jpPainelAspecto.border.title"))); // NOI18N

        jlblLookAndFeel.setText(bundle.getString("Configuracoes.jlblLookAndFeel.text")); // NOI18N

        jcbxLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nativo (Fornecido pelo sistema Operativo)", "Multi-plataforma (Metal)", "Nimbus" }));
        jcbxLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxLookAndFeelActionPerformed(evt);
            }
        });

        jckbUsarAnimacao.setText(bundle.getString("Configuracoes.jckbUsarAnimacao.text")); // NOI18N
        jckbUsarAnimacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckbUsarAnimacaoActionPerformed(evt);
            }
        });

        jlblTipoAnimacao.setText(bundle.getString("Configuracoes.jlblTipoAnimacao.text")); // NOI18N

        jcbxTipoAnimacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cubo", "Dashboard", "Slide" }));
        jcbxTipoAnimacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxTipoAnimacaoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpPainelAspectoLayout = new org.jdesktop.layout.GroupLayout(jpPainelAspecto);
        jpPainelAspecto.setLayout(jpPainelAspectoLayout);
        jpPainelAspectoLayout.setHorizontalGroup(
            jpPainelAspectoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelAspectoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelAspectoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpPainelAspectoLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jlblTipoAnimacao)
                        .add(18, 18, 18)
                        .add(jcbxTipoAnimacao, 0, 422, Short.MAX_VALUE))
                    .add(jpPainelAspectoLayout.createSequentialGroup()
                        .add(jckbUsarAnimacao)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
                    .add(jpPainelAspectoLayout.createSequentialGroup()
                        .add(jlblLookAndFeel)
                        .add(18, 18, 18)
                        .add(jcbxLookAndFeel, 0, 463, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpPainelAspectoLayout.setVerticalGroup(
            jpPainelAspectoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelAspectoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelAspectoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblLookAndFeel)
                    .add(jcbxLookAndFeel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jpPainelAspectoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jckbUsarAnimacao)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpPainelAspectoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblTipoAnimacao)
                    .add(jcbxTipoAnimacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jpTabGeralLayout = new org.jdesktop.layout.GroupLayout(jpTabGeral);
        jpTabGeral.setLayout(jpTabGeralLayout);
        jpTabGeralLayout.setHorizontalGroup(
            jpTabGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpTabGeralLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpTabGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpPainelGeral, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jpPainelAspecto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpTabGeralLayout.setVerticalGroup(
            jpTabGeralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpTabGeralLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelGeral, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpPainelAspecto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jtpTabs.addTab(bundle.getString("Configuracoes.jpTabGeral.TabConstraints.tabTitle"), jpTabGeral); // NOI18N

        jpPainelIvas.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Configuracoes.jpPainelIvas.border.title"))); // NOI18N

        jlblDescricaoIva.setText(bundle.getString("Configuracoes.jlblDescricaoIva.text")); // NOI18N

        jtfNomeIva.setText(bundle.getString("Configuracoes.jtfNomeIva.text")); // NOI18N

        jlblValorIva.setText(bundle.getString("Configuracoes.jlblValorIva.text")); // NOI18N

        jffValorIva.setText(bundle.getString("Configuracoes.jffValorIva.text")); // NOI18N

        jlstIvas.setModel(modeloIvas);
        jscpIvas.setViewportView(jlstIvas);

        jbtnAdicionarIva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/add.png"))); // NOI18N
        jbtnAdicionarIva.setText(bundle.getString("Configuracoes.jbtnAdicionarIva.text")); // NOI18N
        jbtnAdicionarIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarIvaActionPerformed(evt);
            }
        });

        jbtnRemoverIva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/delete.png"))); // NOI18N
        jbtnRemoverIva.setText(bundle.getString("Configuracoes.jbtnRemoverIva.text")); // NOI18N
        jbtnRemoverIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverIvaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpPainelIvasLayout = new org.jdesktop.layout.GroupLayout(jpPainelIvas);
        jpPainelIvas.setLayout(jpPainelIvasLayout);
        jpPainelIvasLayout.setHorizontalGroup(
            jpPainelIvasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelIvasLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelIvasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jscpIvas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .add(jpPainelIvasLayout.createSequentialGroup()
                        .add(jlblDescricaoIva)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtfNomeIva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jlblValorIva)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jffValorIva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnAdicionarIva)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnRemoverIva)))
                .addContainerGap())
        );
        jpPainelIvasLayout.setVerticalGroup(
            jpPainelIvasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelIvasLayout.createSequentialGroup()
                .add(jpPainelIvasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpPainelIvasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jlblDescricaoIva)
                        .add(jtfNomeIva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jlblValorIva)
                        .add(jffValorIva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jbtnAdicionarIva))
                    .add(jbtnRemoverIva))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jscpIvas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpPainelRetencoes.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Configuracoes.jpPainelRetencoes.border.title"))); // NOI18N

        jtfNomeRetencao.setText(bundle.getString("Configuracoes.jtfNomeRetencao.text")); // NOI18N

        jffValorRetencao.setText(bundle.getString("Configuracoes.jffValorRetencao.text")); // NOI18N

        jlblDescricaoRetencao.setText(bundle.getString("Configuracoes.jlblDescricaoRetencao.text")); // NOI18N

        jlblValorRetencao.setText(bundle.getString("Configuracoes.jlblValorRetencao.text")); // NOI18N

        jlstRetencoes.setModel(modeloRetencoes);
        jscpRetencoes.setViewportView(jlstRetencoes);

        jbtnAdicionarRetencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/add.png"))); // NOI18N
        jbtnAdicionarRetencao.setText(bundle.getString("Configuracoes.jbtnAdicionarRetencao.text")); // NOI18N
        jbtnAdicionarRetencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarRetencaoActionPerformed(evt);
            }
        });

        jbtnRemoverRetencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/delete.png"))); // NOI18N
        jbtnRemoverRetencao.setText(bundle.getString("Configuracoes.jbtnRemoverRetencao.text")); // NOI18N
        jbtnRemoverRetencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverRetencaoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpPainelRetencoesLayout = new org.jdesktop.layout.GroupLayout(jpPainelRetencoes);
        jpPainelRetencoes.setLayout(jpPainelRetencoesLayout);
        jpPainelRetencoesLayout.setHorizontalGroup(
            jpPainelRetencoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelRetencoesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelRetencoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jscpRetencoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .add(jpPainelRetencoesLayout.createSequentialGroup()
                        .add(jlblDescricaoRetencao)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtfNomeRetencao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jlblValorRetencao)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jffValorRetencao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnAdicionarRetencao)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnRemoverRetencao)))
                .addContainerGap())
        );
        jpPainelRetencoesLayout.setVerticalGroup(
            jpPainelRetencoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelRetencoesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelRetencoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpPainelRetencoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jtfNomeRetencao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jlblDescricaoRetencao)
                        .add(jlblValorRetencao)
                        .add(jffValorRetencao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jbtnAdicionarRetencao))
                    .add(jbtnRemoverRetencao))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jscpRetencoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jpTabIvasLayout = new org.jdesktop.layout.GroupLayout(jpTabIvas);
        jpTabIvas.setLayout(jpTabIvasLayout);
        jpTabIvasLayout.setHorizontalGroup(
            jpTabIvasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpTabIvasLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpTabIvasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jpPainelIvas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jpPainelRetencoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpTabIvasLayout.setVerticalGroup(
            jpTabIvasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpTabIvasLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelIvas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpPainelRetencoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpTabs.addTab(bundle.getString("Configuracoes.jpTabIvas.TabConstraints.tabTitle"), jpTabIvas); // NOI18N

        jpPainelCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Configuracoes.jpPainelCategorias.border.title"))); // NOI18N

        jlblNome.setText(bundle.getString("Configuracoes.jlblNome.text")); // NOI18N

        jtfNome.setText(bundle.getString("Configuracoes.jtfNome.text")); // NOI18N

        jbtnAdicionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/add.png"))); // NOI18N
        jbtnAdicionarCategoria.setText(bundle.getString("Configuracoes.jbtnAdicionarCategoria.text")); // NOI18N
        jbtnAdicionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarCategoriaActionPerformed(evt);
            }
        });

        jbtnRemoverCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/delete.png"))); // NOI18N
        jbtnRemoverCategoria.setText(bundle.getString("Configuracoes.jbtnRemoverCategoria.text")); // NOI18N
        jbtnRemoverCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverCategoriaActionPerformed(evt);
            }
        });

        jlstCategorias.setModel(modeloCategorias);
        jlstCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jscpCategorias.setViewportView(jlstCategorias);

        org.jdesktop.layout.GroupLayout jpPainelCategoriasLayout = new org.jdesktop.layout.GroupLayout(jpPainelCategorias);
        jpPainelCategorias.setLayout(jpPainelCategoriasLayout);
        jpPainelCategoriasLayout.setHorizontalGroup(
            jpPainelCategoriasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelCategoriasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jscpCategorias, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .add(jpPainelCategoriasLayout.createSequentialGroup()
                        .add(jlblNome)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtfNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jbtnAdicionarCategoria)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnRemoverCategoria)))
                .addContainerGap())
        );
        jpPainelCategoriasLayout.setVerticalGroup(
            jpPainelCategoriasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelCategoriasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblNome)
                    .add(jtfNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jbtnAdicionarCategoria)
                    .add(jbtnRemoverCategoria))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jscpCategorias, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jpTabCategoriasLayout = new org.jdesktop.layout.GroupLayout(jpTabCategorias);
        jpTabCategorias.setLayout(jpTabCategoriasLayout);
        jpTabCategoriasLayout.setHorizontalGroup(
            jpTabCategoriasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpTabCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelCategorias, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTabCategoriasLayout.setVerticalGroup(
            jpTabCategoriasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpTabCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelCategorias, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpTabs.addTab(bundle.getString("Configuracoes.jpTabCategorias.TabConstraints.tabTitle"), jpTabCategorias); // NOI18N

        jlstListaLogs.setModel(modeloLogs);
        jscpListaLogs.setViewportView(jlstListaLogs);

        jtaDadosLog.setColumns(20);
        jtaDadosLog.setRows(5);
        jscpDadosLog.setViewportView(jtaDadosLog);

        jbtnLimparLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/bin.png"))); // NOI18N
        jbtnLimparLogs.setText(bundle.getString("Configuracoes.jbtnLimparLogs.text")); // NOI18N
        jbtnLimparLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparLogsActionPerformed(evt);
            }
        });

        jbtExportarLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/box_down.png"))); // NOI18N
        jbtExportarLogs.setText(bundle.getString("Configuracoes.jbtExportarLogs.text")); // NOI18N
        jbtExportarLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExportarLogsActionPerformed(evt);
            }
        });

        jbtnAplicarFiltroDatas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/jautoinvoice/resources/x16/find.png"))); // NOI18N
        jbtnAplicarFiltroDatas.setText(bundle.getString("Configuracoes.jbtnAplicarFiltroDatas.text")); // NOI18N
        jbtnAplicarFiltroDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAplicarFiltroDatasActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpPainelLogsLayout = new org.jdesktop.layout.GroupLayout(jpPainelLogs);
        jpPainelLogs.setLayout(jpPainelLogsLayout);
        jpPainelLogsLayout.setHorizontalGroup(
            jpPainelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpPainelLogsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jpPainelLogsLayout.createSequentialGroup()
                        .add(jdcFiltroDatas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnAplicarFiltroDatas))
                    .add(jscpListaLogs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpPainelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jpPainelLogsLayout.createSequentialGroup()
                        .add(jbtExportarLogs)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnLimparLogs))
                    .add(jscpDadosLog, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPainelLogsLayout.setVerticalGroup(
            jpPainelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpPainelLogsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jpPainelLogsLayout.createSequentialGroup()
                        .add(jpPainelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jbtnAplicarFiltroDatas)
                            .add(jdcFiltroDatas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jscpListaLogs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                    .add(jpPainelLogsLayout.createSequentialGroup()
                        .add(jscpDadosLog, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jpPainelLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jbtnLimparLogs)
                            .add(jbtExportarLogs))))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jpTabLogsLayout = new org.jdesktop.layout.GroupLayout(jpTabLogs);
        jpTabLogs.setLayout(jpTabLogsLayout);
        jpTabLogsLayout.setHorizontalGroup(
            jpTabLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpTabLogsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelLogs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTabLogsLayout.setVerticalGroup(
            jpTabLogsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpTabLogsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpPainelLogs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpTabs.addTab(bundle.getString("Configuracoes.jpTabLogs.TabConstraints.tabTitle"), jpTabLogs); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(493, Short.MAX_VALUE)
                .add(jbtnGravar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnCancelar)
                .addContainerGap())
            .add(jtpTabs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jtpTabs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnCancelar)
                    .add(jbtnGravar))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jckbUsarAnimacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckbUsarAnimacaoActionPerformed
        jcbxTipoAnimacao.setEnabled(jckbUsarAnimacao.isSelected());
        modificado = true;
    }//GEN-LAST:event_jckbUsarAnimacaoActionPerformed

    private void jbtnExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExplorarActionPerformed
        if (jfc == null) {
            jfc = new JFileChooser();
            jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        }
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jtfFicheiroDados.setText(jfc.getSelectedFile().getAbsolutePath());
            modificado = true;
        }
    }//GEN-LAST:event_jbtnExplorarActionPerformed

    private void jbtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGravarActionPerformed
        if (modificado) {
            String base = System.getProperty("user.home") + File.separator + ".jautoinvoice";
            File directoria = new File(base);

            if (!directoria.exists()) {
                directoria.mkdir();
            }
            try {
                configuracoes.storeToXML(new FileOutputStream(new File(directoria.getAbsolutePath()
                        + File.separator + "conf.xml")), null);

                modificado = false;
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Configuracoes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Configuracoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dispose();
    }//GEN-LAST:event_jbtnGravarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnAplicarFiltroDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAplicarFiltroDatasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAplicarFiltroDatasActionPerformed

    private void jbtExportarLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExportarLogsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtExportarLogsActionPerformed

    private void jbtnLimparLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparLogsActionPerformed
        gestor.limparLogs();
    }//GEN-LAST:event_jbtnLimparLogsActionPerformed

    private void jbtnAdicionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarCategoriaActionPerformed
        if (!jtfNome.getText().trim().isEmpty()) {
            Categoria c = gestor.adicionarCategoria(jtfNome.getText().trim());
            if (c != null) {
                modeloCategorias.addElement(c);
            }
        }
    }//GEN-LAST:event_jbtnAdicionarCategoriaActionPerformed

    private void jbtnRemoverCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverCategoriaActionPerformed
        if (jlstCategorias.getSelectedIndex() >= 0) {
            if (gestor.removerCategoria((Categoria) jlstCategorias.getSelectedValue())) {
                modeloCategorias.remove(jlstCategorias.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_jbtnRemoverCategoriaActionPerformed

    private void jbtnAdicionarIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarIvaActionPerformed
        if (!jtfNomeIva.getText().trim().isEmpty() && !jffValorIva.getValue().toString().isEmpty()) {
            //TODO:
            Iva i = gestor.adicionarIva(jtfNomeIva.getText().trim(), 0.0);
            if (i != null) {
                modeloIvas.addElement(i);
            }
        }
    }//GEN-LAST:event_jbtnAdicionarIvaActionPerformed

    private void jbtnRemoverIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverIvaActionPerformed
        if (jlstIvas.getSelectedIndex() >= 0) {
            if (gestor.removerIva((Iva) jlstIvas.getSelectedValue())) {
                modeloIvas.remove(jlstIvas.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_jbtnRemoverIvaActionPerformed

    private void jbtnAdicionarRetencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarRetencaoActionPerformed
        if (!jtfNomeRetencao.getText().trim().isEmpty() && !jffValorRetencao.getValue().toString().isEmpty()) {
            //TODO: 
            Retencao r = gestor.adicionarRetencao(jtfNomeRetencao.getText().trim(), 0.0);
            if (r != null) {
                modeloRetencoes.addElement(r);
            }
        }
    }//GEN-LAST:event_jbtnAdicionarRetencaoActionPerformed

    private void jbtnRemoverRetencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverRetencaoActionPerformed
        if (jlstRetencoes.getSelectedIndex() >= 0) {
            if (gestor.removerRetencao((Retencao) jlstRetencoes.getSelectedValue())) {
                modeloRetencoes.remove(jlstRetencoes.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_jbtnRemoverRetencaoActionPerformed

    private void jpfPassword2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpfPassword2FocusLost
        String p1 = new String(jpfPassword.getPassword());
        String p2 = new String(jpfPassword2.getPassword());

        //TODO: mensagens de erro
        if (p1.isEmpty()) {
        } else if (p2.isEmpty()) {
        } else if (p1.compareTo(p2) != 0) {
        } else {
            modificado = true;
        }
    }//GEN-LAST:event_jpfPassword2FocusLost

    private void jcbxLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxLookAndFeelActionPerformed
        modificado = true;
    }//GEN-LAST:event_jcbxLookAndFeelActionPerformed

    private void jcbxTipoAnimacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxTipoAnimacaoActionPerformed
        modificado = true;
    }//GEN-LAST:event_jcbxTipoAnimacaoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtExportarLogs;
    private javax.swing.JButton jbtnAdicionarCategoria;
    private javax.swing.JButton jbtnAdicionarIva;
    private javax.swing.JButton jbtnAdicionarRetencao;
    private javax.swing.JButton jbtnAplicarFiltroDatas;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnExplorar;
    private javax.swing.JButton jbtnGravar;
    private javax.swing.JButton jbtnLimparLogs;
    private javax.swing.JButton jbtnRemoverCategoria;
    private javax.swing.JButton jbtnRemoverIva;
    private javax.swing.JButton jbtnRemoverRetencao;
    private javax.swing.JComboBox jcbxLookAndFeel;
    private javax.swing.JComboBox jcbxTipoAnimacao;
    private javax.swing.JCheckBox jckbUsarAnimacao;
    private com.toedter.calendar.JDateChooser jdcFiltroDatas;
    private javax.swing.JFormattedTextField jffValorIva;
    private javax.swing.JFormattedTextField jffValorRetencao;
    private javax.swing.JLabel jlblDescricaoIva;
    private javax.swing.JLabel jlblDescricaoRetencao;
    private javax.swing.JLabel jlblFicheiroDados;
    private javax.swing.JLabel jlblLookAndFeel;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblPassword2;
    private javax.swing.JLabel jlblTipoAnimacao;
    private javax.swing.JLabel jlblValorIva;
    private javax.swing.JLabel jlblValorRetencao;
    private javax.swing.JList jlstCategorias;
    private javax.swing.JList jlstIvas;
    private javax.swing.JList jlstListaLogs;
    private javax.swing.JList jlstRetencoes;
    private javax.swing.JPanel jpPainelAspecto;
    private javax.swing.JPanel jpPainelCategorias;
    private javax.swing.JPanel jpPainelGeral;
    private javax.swing.JPanel jpPainelIvas;
    private javax.swing.JPanel jpPainelLogs;
    private javax.swing.JPanel jpPainelRetencoes;
    private javax.swing.JPanel jpTabCategorias;
    private javax.swing.JPanel jpTabGeral;
    private javax.swing.JPanel jpTabIvas;
    private javax.swing.JPanel jpTabLogs;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPasswordField jpfPassword2;
    private javax.swing.JScrollPane jscpCategorias;
    private javax.swing.JScrollPane jscpDadosLog;
    private javax.swing.JScrollPane jscpIvas;
    private javax.swing.JScrollPane jscpListaLogs;
    private javax.swing.JScrollPane jscpRetencoes;
    private javax.swing.JTextArea jtaDadosLog;
    private javax.swing.JTextField jtfFicheiroDados;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNomeIva;
    private javax.swing.JTextField jtfNomeRetencao;
    private javax.swing.JTabbedPane jtpTabs;
    // End of variables declaration//GEN-END:variables
}
